### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by CradylZeko** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#10]
MacBook-Pro-Andrius:NFTs_Upload_To_OpenSea_With_Metadata-main andrius$ python main.py
  File "main.py", line 30
    def __init__(self, file: str, filetype: str) -> None:
                           ^
SyntaxError: invalid syntax

**Comment by CradylZeko** [comment]
can somebody help, do I do something wrong or it is an error?

**Comment by ZayadZarrani** [comment]
install 
colorama
https://pypi.org/project/colorama/

**Comment by CradylZeko** [comment]
colorama is already installed and I get syntax error

**Comment by nothingatall200** [comment]
I have the same issue!

**Comment by ZayadZarrani** [comment]
I was fix it

Le sam. 15 janv. 2022 à 18:18, nothingatall200 ***@***.***> a
écrit :

**Comment by nothingatall200** [comment]
Can you help? Colorama is installed

**Comment by ZayadZarrani** [comment]
Make anydesk can fix u

Le sam. 15 janv. 2022 à 18:22, nothingatall200 ***@***.***> a
écrit :

**Comment by CradylZeko** [comment]
hey I made anydesk, could you help me?

**Comment by CradylZeko** [comment]
@ZayadZarrani I made any desk can you help me with colorama?

**Comment by ZayadZarranis** [comment]
Can send me message in my IG @zayadiz
To be send me id anydesk
