### ISSUE TITLE
keep getting the error below

### ISSUE THREAD

**Issue by Gitman04** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#12]
Traceback (most recent call last):
File "C:\Users\timot\source\repos\NFTs_Upload_To_OpenSea_With_Metadata\main.py", line 574, in
settings = Settings(file, os.path.splitext(file)[1])
File "C:\Users\timot\source\repos\NFTs_Upload_To_OpenSea_With_Metadata\main.py", line 35, in init
self.file = loads(open(file, encoding='utf-8').read())['nft']
TypeError: list indices must be integers or slices, not str

**Comment by olarichmond** [comment]
someone should find solution to this please

**Comment by olarichmond** [comment]
i need solution please

**Comment by jasperKohn** [comment]
same issue here

**Comment by nftdevs** [comment]
Can you share the content of your metadata.json file? Maybe you missed something there.

**Comment by Gitman04** [comment]
metadata.json file was incorrect found the issue
