### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by olarichmond** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#13]
![Node js command prompt 1_13_2022 6_31_24 PM](https://user-images.githubusercontent.com/97693339/149379831-d086d893-b04c-49ea-a6d8-31b47bf9900d.png)

**Comment by olarichmond** [comment]
please i need solution

**Comment by jasperKohn** [comment]
having the same issue

**Comment by electrical77** [comment]
Same issue. the code seems to be tampered with

**Comment by electrical77** [comment]
> having the same issue

did you get solution yet?

**Comment by nftdevs** [comment]
please check json_structure.json file https://github.com/nftdevs/NFTs_Upload_To_OpenSea_With_Metadata/blob/main/data/json_structure.json
