### ISSUE TITLE
Uploading Failed (File doesn't exists)

### ISSUE THREAD

**Issue by andrewguitar123** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#15]
Here when i get to my last steps and it tells me that my nft doesnt exists... please help me... what should i do

C:\Users\ANDREW\Desktop\new folder\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py:165: DeprecationWarning: executable_path has been deprecated, please pass in a Service object  driver = webdriver.Chrome(self.webdriver_path, options=options)

DevTools listening on ws://127.0.0.1:5225/devtools/browser/e270cc21-4bbe-4332-8e85-911a90e7fafc
Login to MetaMask extension. Logged to Metamask extension.
Login to Opensea. C:\Users\ANDREW\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webelement.py:359: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")
Logged to Opensea.

Uploading Miracle Shiba Trial #1/10. Failed: Message: File doesn't exist.

Uploading Miracle Shiba Trial #2/10. Failed: Message: File doesn't exist.

Uploading Miracle Shiba Trial #3/10. Failed: Message: File doesn't exist.

Uploading Miracle Shiba Trial #4/10. Failed: Message: File doesn't exist.

Uploading Miracle Shiba Trial #5/10. Failed: Message: File doesn't exist.

Uploading Miracle Shiba Trial #6/10. Failed: Message: File doesn't exist.

Uploading Miracle Shiba Trial #7/10. Failed: Message: File doesn't exist.

Uploading Miracle Shiba Trial #8/10. Failed: Message: File doesn't exist.

Uploading Miracle Shiba Trial #9/10. Failed: Message: File doesn't exist.

Uploading Miracle Shiba Trial #10/10. Failed: Message: File doesn't exist.

**Comment by nftdevs** [comment]
Can you please check the value of file_path in metadata.json file

**Comment by andrewguitar123** [comment]
I see, the problem is on the file_path. Thank you very much! I appreciate your effort on all these!

**Comment by ChristianErdtmann** [comment]
Hey i see you upload more than 1 NFT how you do this?
With the json file in the description its me only possible to upload 1 NFT.
What have you done that it uploade more than 1?

**Comment by shirazdelhi** [comment]
> I see, the problem is on the file_path. Thank you very much! I appreciate your effort on all these!

I am also facing the same issue please help
