### ISSUE TITLE
Logs into open sea but stops at image upload.

### ISSUE THREAD

**Issue by SalHenNFT** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#16]
![image](https://user-images.githubusercontent.com/97769938/149638420-aa1e46b0-c2ee-4e14-a3ba-794a29c97bb5.png)

**Comment by nftdevs** [comment]
Can you share the content of your metadata.json file? Maybe you missed something there

**Comment by AbhilashBhoi** [comment]
Hi Peeps,

I am also facing the same issue .

![image](https://user-images.githubusercontent.com/91265310/151713676-cf752243-1158-4786-8dc9-67d2db37bfaa.png)

Please help !

Thanks,
Abhilash

**Comment by coryrobbins** [comment]
same
