### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Intelligencybar** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#17]
<img width="441" alt="Снимок экрана 2022-01-16 231817" src="https://user-images.githubusercontent.com/75547234/149676666-811accc6-71f9-41d7-8024-bcf920eba33d.png">

**Comment by Intelligencybar** [comment]
What's wrong?

**Comment by ZayadZarranis** [comment]
Problem in your json file share with us fix u or make anydesk fix u too
