### ISSUE TITLE
can't log into opensea

### ISSUE THREAD

**Issue by dilana95** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#18]
I'm getting this error please tell me  how to resolve it.

![Capture](https://user-images.githubusercontent.com/80712593/150006028-f22f3a88-907b-456f-8a47-454c640c1728.JPG)

**Comment by LogR1** [comment]
having the same error since a few days now. please help sir

**Comment by shirazdelhi** [comment]
Hi, Even I am having the same issue today, reinstalled chrome and done everything, please help,
Waiting for your reply
Thanks
Shiraz

**Comment by shirazdelhi** [comment]
> having the same error since a few days now. please help sir

Since how many days you facing this error ?

**Comment by shirazdelhi** [comment]
> I'm getting this error please tell me how to resolve it.
> 
> ![Capture](https://user-images.githubusercontent.com/80712593/150006028-f22f3a88-907b-456f-8a47-454c640c1728.JPG)

Since when are you facing this error ?

**Comment by shirazdelhi** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/97992025/150079552-4fce15c6-cf1c-4db9-b630-a6aebac92760.png)

Having this issue since yesterday

**Comment by shirazdelhi** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/97992025/150079817-33f962e9-1200-404e-8ad4-50b10ab21bd2.png)

Having this issue since yesterday

**Comment by lds-dev** [comment]
Exactly the same here since yesterday.

I have also noticed that Opensea has a problem when trying to log in manually with Metamask. Clicking the button takes me to the Metamask download page instead of displaying the extension popup. Obviously I already have the extension installed.

https://user-images.githubusercontent.com/90350379/150141295-8ba9e5e4-1169-4062-a20f-84f7fe8cc69a.mp4

**Comment by LogR1** [comment]
> > having the same error since a few days now. please help sir
> 
> Since how many days you facing this error ?

for less than a week now. how about you? i think opensea made some changes. do know what to do as everything was fine

**Comment by matt4realz** [comment]
Hi All,

I've fixed the issue. 


### The Issue
Apparently, the Metamask button on OpenSea is bugged with constantly opening a URL.

![image](https://user-images.githubusercontent.com/43530617/150248263-7a9519c7-873f-411c-949f-c039414dca39.png)

The only way to fix that, is to first open something else. Thus, I changed the code to click on the "Show More Options" first.
This way, the "Metamask" button is no longer bugged to open a link, and it doesnt affect the rest of the code.

### The Fix : 
In main.py, navigate to **_line 262_**, add a line, then add the following code.

![image](https://user-images.githubusercontent.com/43530617/150248686-6a08c2d8-bc7b-47ec-b1f1-dac47e9f5b65.png)

Try this out, it now works for me, it should work for you too.

**Comment by LogR1** [comment]
PROBLEM FIXED.. THANK YOU BOSS

**Comment by sadeel12** [comment]
please if anyone can share the solution

**Comment by CradylZeko** [comment]
> 

I would like to know the solution too

**Comment by shirazdelhi** [comment]
Yes, even I am facing the same issue.
Please help

**Comment by KhasanLaudry** [comment]
> Hi All,
> 
> I've fixed the issue.

where is the answer?

**Comment by gokhoz** [comment]
> Hi All,
> 
> I've fixed the issue.

What is the solution?

**Comment by Joshi-labs** [comment]
Hey
 
i am facing this issue 

i dont want to open a new chrome browser instance. i want to continue the process after logging in

plzz fix the issue or tell me what to change in the code

**Comment by dilana95** [comment]
Hi all i could fix it by increasing the sleep() parameter. I set it as sleep(5).
