### ISSUE TITLE
OpenSea wont open to allow script to login

### ISSUE THREAD

**Issue by listennman** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#21]
It will login to the Metamask fine, but when it gets there it freezes and the OpenSea tab never opens to complete the login.

**Comment by listennman** [comment]
![error](https://user-images.githubusercontent.com/34762609/150622348-1119cc24-27bd-43a8-8f45-0741b05457fb.PNG)

**Comment by deandrehaijiel** [comment]
im having the same issue :/

**Comment by shirazdelhi** [comment]
I am also having the same issue ..
please help

**Comment by shirazdelhi** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/97992025/150651494-2b9ade9e-cc2b-4a73-8cf6-a3a4e17efa02.png)
![Screenshot_3](https://user-images.githubusercontent.com/97992025/150651504-4b73a9dd-234f-4a7a-aca8-4c6a3c32c3fd.png)


I am also having the same issue ..
please help

**Comment by lucasredway** [comment]
i getting this same error

**Comment by nftdevs** [comment]
Can you get please the latest version of the code
