### ISSUE TITLE
Will this work on mac?

### ISSUE THREAD

**Issue by alessandrohk** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#26]
will this work on mac?

**Comment by alegar44** [comment]
It should... be sure to download the ChromeDriver for Mac... I got mine kind of working, It is installing metamask etc, but stuck with the Cloudflare validation from Opensea.

**Comment by nftdevs** [comment]
We are working on MacOS version.

**Comment by Jakeblackfield** [comment]
So are you sure at the moment it doesn't work on MAC right?

**Comment by nftdevs** [comment]
@Jakeblackfield download latest version of the code. Run pip install -r requirements.txt and then python3 main.py
