### ISSUE TITLE
The script stops after the connection to OpenSea

### ISSUE THREAD

**Issue by jeromebsr** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#27]
Hi there, 

Unfortunately it doesn't work for me 

```
 File "C:\Users\aaa\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x00E46903+2517251]
        Ordinal0 [0x00DDF8E1+2095329]
        Ordinal0 [0x00CE2848+1058888]
        Ordinal0 [0x00D0D448+1233992]
        Ordinal0 [0x00D0D63B+1234491]
        Ordinal0 [0x00D37812+1406994]
        Ordinal0 [0x00D2650A+1336586]
        Ordinal0 [0x00D35BBF+1399743]
        Ordinal0 [0x00D2639B+1336219]
        Ordinal0 [0x00D027A7+1189799]
        Ordinal0 [0x00D03609+1193481]
        GetHandleVerifier [0x00FD5904+1577972]
        GetHandleVerifier [0x01080B97+2279047]
        GetHandleVerifier [0x00ED6D09+534521]
        GetHandleVerifier [0x00ED5DB9+530601]
        Ordinal0 [0x00DE4FF9+2117625]
        Ordinal0 [0x00DE98A8+2136232]
        Ordinal0 [0x00DE99E2+2136546]
        Ordinal0 [0x00DF3541+2176321]
        BaseThreadInitThunk [0x76676739+25]
        RtlGetFullPathName_UEx [0x77E88E7F+1215]
        RtlGetFullPathName_UEx [0x77E88E4D+1165]
```

Where does the error come from ? The script stops at the choice of the wallet although it is connected.
Thanks

**Comment by andrewguitar123** [comment]
same problem here please help us, thank you very much

**Comment by andrewguitar123** [comment]
It still works last week, but not for this week, same problem here please help us, thank you very much

**Comment by musa359** [comment]
Open main.py file, 
and replace this:
```
            if self.element_visible(
                   '//*[@id="main"]/div/div/div/div[2]/ul/li[1]/a/div[2]/span').text == 'MetaMask':
                # Click on Metamask button.
                self.element_clickable('//*[@id="main"]/div/div/div/div[2]/ul/li[1]/a')
                break
```

with:
```
            self.element_clickable('//*[@id="__next"]/div/div[1]/nav/ul/div[2]/li/button')
            
            self.element_clickable('//*[@id="__next"]/div/aside[2]/div[2]/div/div[2]/ul/li[1]/button')
```

**Comment by elwanm** [comment]
> Open main.py file, and replace this:
> 
> ```
>             if self.element_visible(
>                    '//*[@id="main"]/div/div/div/div[2]/ul/li[1]/a/div[2]/span').text == 'MetaMask':
>                 # Click on Metamask button.
>                 self.element_clickable('//*[@id="main"]/div/div/div/div[2]/ul/li[1]/a')
>                 break
> ```
> 
> with:
> 
> ```
>             self.element_clickable('//*[@id="__next"]/div/div[1]/nav/ul/div[2]/li/button')
>             
>             self.element_clickable('//*[@id="__next"]/div/aside[2]/div[2]/div/div[2]/ul/li[1]/button')
> ```

can you please upload the full main.py file to google drive .... am still getting stuck at the wallet

**Comment by jackaru** [comment]
@musa359 Mmmh, I got a fullscreen QR code now,

**Comment by tusharhrb** [comment]
> @musa359 Mmmh, I got a fullscreen QR code after replacing the code

rerun the same code .... its not your fault instead its opensea which places position of metamask on button[1] and sometime on buttion[2] ..... just rerun the same code ...... sometime it took me 4 times to rerun to get the result

**Comment by patriotboyz** [comment]
Can't seem to get past this one

C:\Users\jpatc\OneDrive\Documents\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py:165: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(self.webdriver_path, options=options)

DevTools listening on ws://127.0.0.1:57292/devtools/browser/f95a7a82-281f-40f6-bb3a-a34f774ab457
Login to MetaMask extension. Traceback (most recent call last):
  File "C:\Users\jpatc\OneDrive\Documents\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 577, in <module>
    opensea.metamask()  # Connect to MetaMask.
  File "C:\Users\jpatc\OneDrive\Documents\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 246, in metamask
    self.element_clickable(
  File "C:\Users\jpatc\OneDrive\Documents\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 172, in element_clickable
    WDW(self.driver, 5).until(EC.element_to_be_clickable(
  File "C:\Users\jpatc\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


C:\Users\jpatc\OneDrive\Documents\NFTs_Upload_To_OpenSea_With_Metadata-main>python main.py
  File "C:\Users\jpatc\OneDrive\Documents\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 266
    self.element_clickable('//*[@id="__next"]/div/div[1]/nav/ul/div[2]/li/button')
IndentationError: unexpected indent

C:\Users\jpatc\OneDrive\Documents\NFTs_Upload_To_OpenSea_With_Metadata-main>python main.py
  File "C:\Users\jpatc\OneDrive\Documents\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 266
    self.element_clickable('//*[@id="__next"]/div/div[1]/nav/ul/div[2]/li/button')
IndentationError: unexpected indent

C:\Users\jpatc\OneDrive\Documents\NFTs_Upload_To_OpenSea_With_Metadata-main>

**Comment by patriotboyz** [comment]
keep running into this error after replacing the code. I've re run it numerous time

![image](https://user-images.githubusercontent.com/98916127/152273752-b5b07f70-2fea-4409-a537-4eb87d9e7577.png)

**Comment by Trevas2022** [comment]
So the fix I found for this would be running the code as is, and when it reaches the Opensea login page. Manually click the Show More Options button on the wallet list before the code stops running. I changed the time to be longer in the code so that I could have enough time to click the button and let the code continue on its own. So far no issues uploading and the code is working fine now. Hope this helps for now folks!

**Comment by patriotboyz** [comment]
Great, thank you. Do I just copy the edited code or is it downloadable?

**Comment by jackaru** [comment]
@Trevas2022  I came to this conclusion too, the other problem is when it selects the blockchain (in my case polygon) ... it doesn't select but keeps the selection popup open with the 2 items ethereum or polygon

**Comment by patriotboyz** [comment]
exactly the same here.
