### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by AbhilashBhoi** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#28]
Hi Peeps,

I am facing the below issue .

![image](https://user-images.githubusercontent.com/91265310/151713724-a35dfc12-27ea-4e68-b649-1e84c5d30539.png)

Please help !

Thanks,
Abhilash

**Comment by TallishDev** [comment]
I had a same problem. I just had to add missing json keys even if they were empty
