### ISSUE TITLE
Helllp ASAP! I'M HAVING PROBLEM AFTER SELECTING THE NUMBER OF FILE. PLSSS HELP

### ISSUE THREAD

**Issue by SakoDG** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#29]
Helllp ASAP! I'M HAVING PROBLEM AFTER SELECTING THE NUMBER OF FILE. PLSSS HELP, 
I'm selecting the number of the file and then...

Traceback (most recent call last):
  File "C:\Users\USER\Desktop\New folder (3)\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 574, in <module>
    settings = Settings(file, os.path.splitext(file)[1])
  File "C:\Users\USER\Desktop\New folder (3)\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 35, in __init__
    self.file = loads(open(file, encoding='utf-8').read())['nft']
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 56 column 7 (char 1309)

please help me ASAP

**Comment by SakoDG** [comment]
I solved the issue  .

**Comment by ManikClub** [comment]
How? Because I'm getting the same...

Exception has occurred: JSONDecodeError
Invalid control character at: line 4 column 60 (char 75)
  File "[X:\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py]()", line 35, in __init__
    self.file = loads(open(file, encoding='utf-8').read())['nft']
  File "[X:\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py]()", line 574, in <module>
    settings = Settings(file, os.path.splitext(file)[1])

**Comment by SakoDG** [comment]
HI, CAN YOU COPY YOUR METADATA FILE AND SEND IT TO ME, SO I CAN FIX IT, OR SEND THE WHOLE FILE.

**Comment by shirazdelhi** [comment]
Email me on ***@***.***

**Comment by SakoDG** [comment]
The email is not showing on github

**Comment by shirazdelhi** [comment]
***@***.***

**Comment by ManikClub** [comment]
you mean the main.py file?

**Comment by SakoDG** [comment]
no, metadata json file

**Comment by shirazdelhi** [comment]
Do you want the main.py file ?

**Comment by SakoDG** [comment]
no, the metadata json file

**Comment by SakoDG** [comment]
guys, this is number of whatsapp, +1 913 732 4669

**Comment by ManikClub** [comment]
here you go
[_metadata.zip](https://github.com/nftdevs/NFTs_Upload_To_OpenSea_With_Metadata/files/8003913/_metadata.zip)

**Comment by shirazdelhi** [comment]
let us know if this works for you

**Comment by SakoDG** [comment]
manikclub one minute i will try to solve it

**Comment by ManikClub** [comment]
thanks

**Comment by shirazdelhi** [comment]
Working ?

**Comment by SakoDG** [comment]
look, can you send to me the whole nft file, cause i will try it and see if it is working

**Comment by ManikClub** [comment]
you realise how shady that looks, right? I mean

**Comment by SakoDG** [comment]
yeah, the coding it's a bit hard, but can you send the nft file so i can solve it surely

**Comment by SakoDG** [comment]
or send the main.py

**Comment by ManikClub** [comment]
[main.zip](https://github.com/nftdevs/NFTs_Upload_To_OpenSea_With_Metadata/files/8004025/main.zip)

**Comment by SakoDG** [comment]
ok, i will try to solve it in asap

**Comment by SakoDG** [comment]
HI, I'M SO SORRY BECAUSE I CAN'T SOLVE THIS, I TRIED BUT IT'S FROM YOUR METADATA FILE, I RECOMEND THAT YOU RESTORE YOUR METADATA.JSON FILE AND DON'T EDIT ANYTHING IN IT, SORRY
