### ISSUE TITLE
2 things

### ISSUE THREAD

**Issue by SeanFrohman** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#35]
I'm using the other one as we speak and it's been 24 hours and it's uploaded 2500 so far.

I'm very thankful for this but should I have used this one for some reason? 

Also I was looking for a place to donate and I found out the best way to donate to someone who you can't figure that out for is to open an issue and ask them yourself where to donate. I was just going to send you some Bitcoin or whatever. Cash idc.

**Comment by maximedrn** [comment]
> Hello @SeanFrohman Thank you! 0x6Eee50275b6E1BE0aB0D2785E00330d3b8526dB5

For real? You steal my code and ask for donation.
You should not be able to share on GitHub...
