### ISSUE TITLE
Now there is a captcha when creating nft

### ISSUE THREAD

**Issue by agungsantoso** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#37]
Starting today there is a captcha when creating nft how to automaticlly solve the captcha?

**Comment by Kanishka-Chandra** [comment]
Hey man did you find any solution to this, I am facing the same problem

**Comment by shirazdelhi** [comment]
No not yet

**Comment by shirazdelhi** [comment]
sab chuitya bana rahe hai bahrwe

**Comment by nftdevs** [comment]
We are working on it.

**Comment by nftdevs** [comment]
Can you please get the latest version of the code and run:
- pip install -r requirements.txt
- python main.py

**Comment by ib4ngz** [comment]
@Amogha-Maiya Solved.

**Comment by nftdevs** [comment]
> @nftdevs captcha problem is solved in your new Code???

Yes, we have a workaround.
