### ISSUE TITLE
Chrome driver issue

### ISSUE THREAD

**Issue by pr9c1s9** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#38]
My Google Chrome version is 98.0.4758.82 but driver version supports only 96 version. I tried to install new driver but after installation main.py tells me that driver is still supports 96 version only. I tried to reinstall chrome but no result. Also I tried to install different versions of driver. Do you have any suggestions?

**Comment by Jorddd** [comment]
Hi @pr9c1s9 Have you resolved your issue? If yes, can you tell how? Thanks
