### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by ChristianErdtmann** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#4]
Hey my .jason lock like described but i got this error:

Traceback (most recent call last):
  File "C:\NFTMinter09_01\NFTs_Upload_To_OpenSea_With_Metadata\main.py", line 574, in <module>
    settings = Settings(file, os.path.splitext(file)[1])
  File "C:\NFTMinter09_01\NFTs_Upload_To_OpenSea_With_Metadata\main.py", line 35, in __init__
    self.file = loads(open(file, encoding='utf-8').read())['nft']
TypeError: list indices must be integers or slices, not str

Here is my jason file:
[
  {
    "file_url": "C:NFTMinter1000Oversea_0_600\u000bideo-source-code-create-nft-collection\buildimages/1.png",
    "nft_name": "Simple Aliens Club #1",
    "external_link": "https://simple-alien-metaverse-club.com",
    "description": "Simple Aliens Club",
    "collection": "CRYPTOALIENS TEST",
    "properties": [
      {
        "trait_type": "Backgrounds",
        "value": "b4"
      },
      {
        "trait_type": "Body",
        "value": "bd1"
      },
      {
        "trait_type": "Klamotten",
        "value": "k3"
      },
      {
        "trait_type": "Augen",
        "value": "b1"
      },
      {
        "trait_type": "Iris",
        "value": "i5"
      },
      {
        "trait_type": "Mund",
        "value": "m4"
      },
      {
        "trait_type": "Frisur",
        "value": "F19"
      }
    ],
    "levels": [
      {
        "name": "Speed",
        "from": 2,
        "to": 5
      },
      {
        "name": "Width",
        "from": 2,
        "to": 15
      },
      {
        "name": "Strenght",
        "from": 1,
        "to": 10
      },
      {
        "name": "Age",
        "from": 1,
        "to": 9
      }
    ],
	      "unlockable_content": [
        true,
        "Content"
      ],

    "custom_fields": {
      "explicit_and_sensitive_content": true,
      "supply": 1,
      "blockchain": "Polygon",
      "price": 0.005,
      "quantity": 1
    }
  }
]

**Comment by ChristianErdtmann** [comment]
Ok fount it there was missing the nft at beginning but now i got the error 

Traceback (most recent call last):
  File "C:\NFTMinter09_01\NFTs_Upload_To_OpenSea_With_Metadata\main.py", line 574, in <module>
    settings = Settings(file, os.path.splitext(file)[1])
  File "C:\NFTMinter09_01\NFTs_Upload_To_OpenSea_With_Metadata\main.py", line 35, in __init__
    self.file = loads(open(file, encoding='utf-8').read())['nft']
  File "C:\Users\Christian\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Christian\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Christian\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 2 column 6 (char 7)

But there is no , missing it looks like the jason in the description.

[
"nft": [
  {
    "file_url": "C:NFTMinter1000Oversea_0_600\u000bideo-source-code-create-nft-collection\buildimages/1.png",
    "nft_name": "Simple Aliens Club #1",
    "external_link": "https://simple-alien-metaverse-club.com",
    "description": "Simple Aliens Club",
    "collection": "CRYPTOALIENS TEST",
    "properties": [
      {
        "trait_type": "Backgrounds",
        "value": "b4"
      },
      {
        "trait_type": "Body",
        "value": "bd1"
      },
      {
        "trait_type": "Klamotten",
        "value": "k8"
      },
      {
        "trait_type": "Augen",
        "value": "b1"
      },
      {
        "trait_type": "Iris",
        "value": "i2"
      },
      {
        "trait_type": "Mund",
        "value": "m2_r"
      },
      {
        "trait_type": "Frisur",
        "value": "F4"
      }
    ],
    "levels": [
      {
        "name": "Speed",
        "from": 2,
        "to": 5
      },
      {
        "name": "Width",
        "from": 2,
        "to": 15
      },
      {
        "name": "Strenght",
        "from": 1,
        "to": 10
      },
      {
        "name": "Age",
        "from": 1,
        "to": 9
      }
    ],
	      "unlockable_content": [
        true,
        "Content"
      ],
    "custom_fields": {
      "explicit_and_sensitive_content": true,
      "supply": 1,
      "blockchain": "Polygon",
      "price": 0.005,
      "quantity": 1
    }
  }
  ]
]

**Comment by ChristianErdtmann** [comment]
Found the issue

**Comment by Gitman04** [comment]
> 

What was the issue? having the same problem ;

Traceback (most recent call last):
  File "C:\Users\timot\source\repos\NFTs_Upload_To_OpenSea_With_Metadata\main.py", line 574, in <module>
    settings = Settings(file, os.path.splitext(file)[1])
  File "C:\Users\timot\source\repos\NFTs_Upload_To_OpenSea_With_Metadata\main.py", line 35, in __init__
    self.file = loads(open(file, encoding='utf-8').read())['nft']
TypeError: list indices must be integers or slices, not str

**Comment by jasperKohn** [comment]
could you explain what you did to fix it?


> Found the issue

**Comment by ChristianErdtmann** [comment]
your jason file is not in the correct format like described. In my cause the "NFT" String was missing on top

**Comment by SalHenNFT** [comment]
> your jason file is not in the correct format like described. In my cause the "NFT" String was missing on top

What does your updated json file look like with the NFT string added so i can update mine

**Comment by coryrobbins** [comment]
I am receiving the following error:  

line 82, in type_parameters
parameters[element] = str(parameters[element])
TypeError: 'str' object does not support item assignment
