### ISSUE TITLE
How to solve captcha

### ISSUE THREAD

**Issue by ib4ngz** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#40]
Every first nft upload won't ask for a captcha and it sure did when I tested it. maybe the browser should be clear of cookies. so can you fix this code for me? maybe make it repeat the process of opening browser -> metamask -> opensea... after first successful nft upload.
your source code is very useful for me, i really appreciate if you can fix it.

**Comment by Mohammadkhare** [comment]
its my problem too

**Comment by Kisnobeats** [comment]
Same here. I am trying to figure  out if changing the amount of time it logs in the information would help. Iunno, but I hoe a solution comes our way soon!

**Comment by ib4ngz** [comment]
Changing the amount of time probably won't have much effect, the Captcha on opensea will appear on the second nft upload, and on average every next 10 uploads.

**Comment by ib4ngz** [comment]
Changing the amount of time probably won't have much effect, captcha on opensea will appear on the second nft upload, and on average every next 10 uploads.

**Comment by nftdevs** [comment]
Can you please get the latest version of the code and run:
- pip install -r requirements.txt
- python main.py

**Comment by ib4ngz** [comment]
Solved, thank you

**Comment by ib4ngz** [comment]
Captcha problem solved!  Thanks to @nftdevs

**Comment by ib4ngz** [comment]
Solved! Thanks to @nftdevs

**Comment by ib4ngz** [comment]
Solved, Thank you @nftdevs

**Comment by ib4ngz** [comment]
Auto NFT sell for next project. haha just kidding :D
