### ISSUE TITLE
Collection Name is not replaced

### ISSUE THREAD

**Issue by ChristianErdtmann** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#5]
I allready have collections.
When i now start the main.py
everithing works fine.
But it dont replace the Collection it appends the specified collection name to that of the existing collection.

An so i get the error:
Uploading NFT #1/1. Failed: Message: Collection doesn't exist

**Comment by MoistBrownie** [comment]
I am also having this issue, I found if I click on the dropdown box to select collections, it fixes itself and continues, however I must do this for every uploaded NFT which eliminates the entire purpose of doing it automatically.

**Comment by MoistBrownie** [comment]
I have found a workaround, just go to the end of line 340 (should be if settings.collection != '':) press enter to go to a new line and paste in:
self.clear_text(
                    '//*[@id="__next"]/div[1]/main/div/div/section/div/form/'
                    'div[5]/div/div[2]/input'
                )

This fixed the issue for me.

**Comment by nftdevs** [comment]
Hi, can you please try to add sleep(3) above line 343 (main.py)[https://github.com/nftdevs/NFTs_Upload_To_OpenSea_With_Metadata/blob/main/main.py#L343](https://github.com/nftdevs/NFTs_Upload_To_OpenSea_With_Metadata/blob/main/main.py#L343)

**Comment by MoistBrownie** [comment]
> Hi, can you please try to add sleep(3) above line 343 (main.py)https://github.com/nftdevs/NFTs_Upload_To_OpenSea_With_Metadata/blob/main/main.py#L343

I actually did find a solution, I repurposed some code I found in another part of the file for clearing all text in an element. I then directed it to the correct element right before the code pasted the collection name, so the text is cleared and then new texed is pasted in.
