### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by abdurrehmanRasheed12** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#63]
I have put my collection on sale using this script but it was only put up on sale for 7 days, Now I again need to put it up on sale for 6 months , Is there any way I can do that?
Any help would be appreciated

**Comment by nftdevs** [comment]
You can change the duration in main.py file on line 164 -> https://github.com/nftdevs/NFTs_Upload_To_OpenSea_With_Metadata/blob/main/main.py#L164
