### ISSUE TITLE
NFT sale cancelled: Message:

### ISSUE THREAD

**Issue by GangstaGaming** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#8]
I have a small problem at the very end. Everything goes well until it tries to sell the nft. It doesn't work and it gives me an error in command prompt saying "NFT sale cancelled". I would appreciate any help. Thank you!

**Comment by dtlb324** [comment]
You need to buy a Ethereum token on Opensea so that Opensea is connected to your wallet. Once that happens, the error message should go away.

**Comment by barrada** [comment]
I have the same problem.. everything works fine until after create, metamask window opens to verify sell and gets stuck there, and i get the same message NFT sale cancelled, then it goes onto uploading the second NFT. Please advise

**Comment by MSBOSS616** [comment]
> > 
> 
> Yeah I recently uploaded all 10,000 of my NFTs, but now I'm still looking for another script just to sell them.

bro if you find a good working code please do tell here also

**Comment by GangstaGaming** [comment]
> bro if you find a good working code please do tell here also

I will! Please do the same if you find one! I'm trying to look for a macro or something that will do it.
